language: java
jdk: oraclejdk8
install: 
    - "mvn -N io.takari:maven:wrapper"
    - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: 
    - ./mvnw clean install
    - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
